# Generated by Django 4.1.7 on 2023-03-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_musicuploaders_delete_musicuploader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('albums', models.ImageField(upload_to='myapp/video')),
                ('file', models.FileField(upload_to='myapp/video')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
