# Generated by Django 4.1.7 on 2023-03-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('new', models.TextField()),
                ('image', models.ImageField(upload_to='myapp/news')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='topArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_realname', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('record_label', models.CharField(max_length=255)),
                ('genrie', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('award', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='trendingArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_realname', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('record_label', models.CharField(max_length=255)),
                ('genrie', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('award', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
