# Generated by Django 4.1.7 on 2023-03-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_news_topartist_trendingartist'),
    ]

    operations = [
        migrations.CreateModel(
            name='topArtists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_realname', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('record_label', models.CharField(max_length=255)),
                ('genrie', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='myapp/bio')),
                ('award', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='trendingArtists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_realname', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('record_label', models.CharField(max_length=255)),
                ('genrie', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='myapp/bio')),
                ('award', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='topArtist',
        ),
        migrations.DeleteModel(
            name='trendingArtist',
        ),
    ]
