# Generated by Django 4.1.7 on 2023-03-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_new_delete_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicuploaders',
            options={'ordering': ('-id',)},
        ),
    ]
