# Generated by Django 4.1.7 on 2023-03-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_new_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={},
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(upload_to='news'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
