# Generated by Django 4.1.7 on 2023-03-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_new_options_alter_new_image_alter_new_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='updateNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='myapp/static')),
                ('date', models.CharField(max_length=255)),
            ],
        ),
    ]
