# Generated by Django 4.1.7 on 2023-04-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_movies_delete_movie_alter_updatenew_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ('-id',)},
        ),
    ]
