# Generated by Django 4.1.7 on 2023-04-19 10:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_new_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicuploaders',
            name='albums',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='musicuploaders',
            name='songs',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
